SecRule REMOTE_ADDR "@ipMatch 82.67.60.71" \
    "id:1001,\
    phase:1,\
    block,\
    msg:'Denied for address 82.67.60.71',\
    logdata:'IP blocked %{REMOTE_ADDR}',\
    severity:'CRITICAL',\
    tag:'ip-blocking'"
